
import { EducationLevel, StudyFormat, Program, Advantage } from './types';

export const ADVANTAGES: Advantage[] = [
  {
    title: 'Лицензия и аккредитация',
    shortDesc: 'Диплом государственного образца · Бессрочная аккредитация',
    fullDesc: 'Лицензия и аккредитация Минобрнауки дают вузу право официально обучать и гарантируют, что твоё обучение будет признано государством и работодателями',
    icon: 'ShieldCheck'
  },
  {
    title: 'Государственный диплом',
    shortDesc: 'Признаётся всеми работодателями РФ и за рубежом',
    fullDesc: 'Наши выпускники получают документы установленного образца, подтверждающие квалификацию в соответствии с ФГОС.',
    icon: 'GraduationCap'
  },
  {
    title: 'Программы под реальный рынок',
    shortDesc: 'Учебные планы разработаны совместно с экспертами рынка',
    fullDesc: 'Мы фокусируемся на навыках, которые реально требуются работодателям. Практика начинается с первого курса.',
    icon: 'TrendingUp'
  },
  {
    title: 'Гибкий график обучения',
    shortDesc: 'Очно, заочно, онлайн · Учись без отрыва от карьеры',
    fullDesc: 'Возможность совмещать работу и учебу благодаря современным форматам и индивидуальным траекториям.',
    icon: 'Calendar'
  },
  {
    title: 'Преподаватели-практики',
    shortDesc: '70% состава — действующие специалисты индустрии',
    fullDesc: 'Лекции ведут архитекторы, юристы, дизайнеры и психологи с реальным опытом в крупнейших компаниях. Среди преподавателей — профессора и мастера: В.М. Фильштинский (театр), В.Ю. Богатырев (музыка и кино), заведующие кафедрами архитектуры, дизайна, строительства.',
    icon: 'Users'
  },
  {
    title: 'Прозрачно и доступно',
    shortDesc: 'Рассрочка 0% · Стоимость от 46 000 ₽/год',
    fullDesc: 'Для платных программ предусмотрена рассрочка без переплат — можно платить помесячно или по семестрам. Стоимость обучения в СЗУ — от 46 000 ₽ в год в зависимости от направления и формы обучения.',
    icon: 'MapPin'
  }
];

// Данные направлений обучения по официальному сайту СЗУ: https://szu.ru/directions-of-training
export const PROGRAMS_DATA: Program[] = [
  // ——— Высшее образование – бакалавриат ———
  {
    id: '07.03.01',
    code: '07.03.01',
    level: EducationLevel.BACHELOR,
    name: 'Архитектура',
    specialization: 'Теория и практика архитектуры',
    duration: '4 года',
    durationValue: 4,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Математика; Творческое испытание',
    passingScore: 245,
    description: 'Комплексная подготовка архитекторов, способных проектировать здания, градостроительные ансамбли и интерьеры.'
  },
  {
    id: '07.03.02',
    code: '07.03.02',
    level: EducationLevel.BACHELOR,
    name: 'Реставрация архитектуры',
    specialization: 'Архитектурное наследие',
    duration: '4 года',
    durationValue: 4,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Математика; Творческое испытание',
    passingScore: 230,
    description: 'Сохранение и восстановление памятников архитектуры и градостроительства.'
  },
  {
    id: '07.03.04',
    code: '07.03.04',
    level: EducationLevel.BACHELOR,
    name: 'Градостроительство',
    specialization: 'Проектирование городской среды',
    duration: '4 года',
    durationValue: 4,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Математика; Творческое испытание',
    passingScore: 215,
    description: 'Планирование и развитие городских территорий, ландшафтная архитектура.'
  },
  {
    id: '08.03.01',
    code: '08.03.01',
    level: EducationLevel.BACHELOR,
    name: 'Строительство',
    specialization: 'Промышленное и гражданское строительство',
    duration: '4 года',
    durationValue: 4,
    price: 250000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'ЕГЭ: Русский, Математика, Физика/Химия/Информатика',
    passingScore: 180,
    description: 'Инженерная подготовка специалистов для строительной отрасли.'
  },
  {
    id: '38.03.01',
    code: '38.03.01',
    level: EducationLevel.BACHELOR,
    name: 'Экономика',
    specialization: 'Экономика и управление',
    duration: '4 года',
    durationValue: 4,
    price: 220000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'ЕГЭ: Русский, Математика, Обществознание',
    passingScore: 185,
    description: 'Подготовка экономистов для предприятий, госструктур и аналитики.'
  },
  {
    id: '38.03.02',
    code: '38.03.02',
    level: EducationLevel.BACHELOR,
    name: 'Менеджмент',
    specialization: 'Менеджмент в культуре',
    duration: '4 года',
    durationValue: 4,
    price: 220000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'ЕГЭ: Русский, Математика, История/Обществознание',
    passingScore: 170,
    description: 'Управление организациями в сфере культуры и бизнеса.'
  },
  {
    id: '38.03.05',
    code: '38.03.05',
    level: EducationLevel.BACHELOR,
    name: 'Бизнес-информатика',
    specialization: 'IT в бизнесе',
    duration: '4 года',
    durationValue: 4,
    price: 250000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Математика, Информатика',
    passingScore: 210,
    description: 'Стык информационных технологий и менеджмента.'
  },
  {
    id: '40.03.01',
    code: '40.03.01',
    level: EducationLevel.BACHELOR,
    name: 'Юриспруденция',
    specialization: 'Юридическая практика',
    duration: '4 года',
    durationValue: 4,
    price: 220000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'ЕГЭ: Русский, Обществознание, История',
    passingScore: 200,
    description: 'Подготовка квалифицированных юристов для всех отраслей права.'
  },
  {
    id: '50.03.03',
    code: '50.03.03',
    level: EducationLevel.BACHELOR,
    name: 'История искусств',
    specialization: 'Искусствоведение',
    duration: '4 года',
    durationValue: 4,
    price: 180000,
    format: [StudyFormat.FULL_TIME, StudyFormat.REMOTE],
    exams: 'ЕГЭ: Русский, История; Творческое испытание',
    passingScore: 190,
    description: 'Изучение истории мирового и отечественного искусства.'
  },
  {
    id: '51.03.01',
    code: '51.03.01',
    level: EducationLevel.BACHELOR,
    name: 'Культурология',
    specialization: 'Теория и история культуры',
    duration: '4 года',
    durationValue: 4,
    price: 180000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'ЕГЭ: Русский, История, Обществознание',
    passingScore: 185,
    description: 'Изучение культуры, культурных практик и управления в сфере культуры.'
  },
  {
    id: '37.03.01',
    code: '37.03.01',
    level: EducationLevel.BACHELOR,
    name: 'Психология',
    specialization: 'Клиническая психология',
    duration: '4 года',
    durationValue: 4,
    price: 200000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'ЕГЭ: Русский, Биология, Обществознание/Математика',
    passingScore: 195,
    description: 'Обучение методам психологической помощи и диагностики.'
  },
  {
    id: '54.03.01',
    code: '54.03.01',
    level: EducationLevel.BACHELOR,
    name: 'Дизайн',
    specialization: 'Графический дизайн / Дизайн среды',
    duration: '4 года',
    durationValue: 4,
    price: 300000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'ЕГЭ: Русский, Литература; Творческое испытание',
    passingScore: 240,
    description: 'Художественное проектирование объектов визуальных коммуникаций.'
  },
  {
    id: '54.03.04',
    code: '54.03.04',
    level: EducationLevel.BACHELOR,
    name: 'Реставрация ДПИ и живописи',
    specialization: 'Реставрация декоративно-прикладного искусства и живописи',
    duration: '4 года',
    durationValue: 4,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Литература; Творческое испытание',
    passingScore: 235,
    description: 'Сохранение произведений искусства и предметов старины.'
  },

  // ——— Высшее образование – магистратура ———
  {
    id: '07.04.01',
    code: '07.04.01',
    level: EducationLevel.MASTER,
    name: 'Архитектура',
    specialization: 'Инновации в архитектуре',
    duration: '2 года',
    durationValue: 2,
    price: 280000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Портфолио, собеседование',
    passingScore: 80,
    description: 'Углубленное изучение архитектурной науки и проектирования.'
  },
  {
    id: '07.04.02',
    code: '07.04.02',
    level: EducationLevel.MASTER,
    name: 'Реконструкция и реставрация архитектурного наследия',
    specialization: 'Историко-архитектурное наследие',
    duration: '2 года',
    durationValue: 2,
    price: 280000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Портфолио, собеседование',
    passingScore: 80,
    description: 'Подготовка специалистов в области реставрации и реконструкции памятников архитектуры.'
  },
  {
    id: '07.04.04',
    code: '07.04.04',
    level: EducationLevel.MASTER,
    name: 'Градостроительство',
    specialization: 'Проектирование и развитие территорий',
    duration: '2 года',
    durationValue: 2,
    price: 280000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Портфолио, собеседование',
    passingScore: 80,
    description: 'Магистерская подготовка в области градостроительного планирования.'
  },
  {
    id: '08.04.01',
    code: '08.04.01',
    level: EducationLevel.MASTER,
    name: 'Строительство',
    specialization: 'Строительные конструкции и технологии',
    duration: '2 года',
    durationValue: 2,
    price: 250000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'Собеседование по направлению',
    passingScore: 70,
    description: 'Углубленная инженерная подготовка для строительной отрасли.'
  },
  {
    id: '38.04.05',
    code: '38.04.05',
    level: EducationLevel.MASTER,
    name: 'Бизнес-информатика',
    specialization: 'Цифровая трансформация бизнеса',
    duration: '2 года',
    durationValue: 2,
    price: 250000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Собеседование, портфолио',
    passingScore: 75,
    description: 'Управление IT-проектами и информационными системами в организациях.'
  },
  {
    id: '54.04.01',
    code: '54.04.01',
    level: EducationLevel.MASTER,
    name: 'Дизайн',
    specialization: 'Стратегический дизайн',
    duration: '2 года',
    durationValue: 2,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Портфолио, собеседование',
    passingScore: 90,
    description: 'Дизайн-менеджмент и разработка сложных дизайн-систем.'
  },
  {
    id: '54.04.04',
    code: '54.04.04',
    level: EducationLevel.MASTER,
    name: 'Реставрация',
    specialization: 'Реставрация объектов культурного наследия',
    duration: '2 года',
    durationValue: 2,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Портфолио, собеседование',
    passingScore: 85,
    description: 'Научно-практическая подготовка реставраторов высшей квалификации.'
  },

  // ——— Высшее образование – специалитет ———
  {
    id: '52.05.01',
    code: '52.05.01',
    level: EducationLevel.SPECIALIST,
    name: 'Актерское искусство',
    specialization: 'Артист театра и кино',
    duration: '4 года',
    durationValue: 4,
    price: 280000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Литература; Творческое испытание',
    passingScore: 270,
    description: 'Профессиональное мастерство актера в лучших традициях театральной школы.'
  },
  {
    id: '55.05.01-igr',
    code: '55.05.01',
    level: EducationLevel.SPECIALIST,
    name: 'Режиссура кино и телевидения',
    specialization: 'Режиссер игрового кино- и телефильма',
    duration: '5 лет',
    durationValue: 5,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Литература; Творческое испытание',
    passingScore: 265,
    description: 'Все этапы создания кинофильма: от сценария до пост-продакшена.'
  },
  {
    id: '55.05.01-mm',
    code: '55.05.01',
    level: EducationLevel.SPECIALIST,
    name: 'Режиссура кино и телевидения',
    specialization: 'Режиссер мультимедиа',
    duration: '5 лет',
    durationValue: 5,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Литература; Творческое испытание',
    passingScore: 260,
    description: 'Режиссура мультимедийных проектов, интерактивных и медиапродуктов.'
  },
  {
    id: '54.05.02',
    code: '54.05.02',
    level: EducationLevel.SPECIALIST,
    name: 'Живопись',
    specialization: 'Станковая живопись',
    duration: '5 лет',
    durationValue: 5,
    price: 300000,
    format: [StudyFormat.FULL_TIME],
    exams: 'ЕГЭ: Русский, Литература; Творческое испытание',
    passingScore: 255,
    description: 'Академическое художественное образование, станковая живопись.'
  },

  // ——— Подготовка научных и научно-педагогических кадров в аспирантуре ———
  {
    id: '2.1.11',
    code: '2.1.11',
    level: EducationLevel.POSTGRADUATE,
    name: 'Теория и история архитектуры, реставрация и реконструкция историко-архитектурного наследия',
    specialization: 'Научная специальность',
    duration: '3–4 года',
    durationValue: 4,
    price: 150000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'Вступительные испытания по специальности',
    passingScore: 0,
    description: 'Подготовка кандидатов наук в области архитектуры и реставрации.'
  },
  {
    id: '5.2.2',
    code: '5.2.2',
    level: EducationLevel.POSTGRADUATE,
    name: 'Математические, статистические и инструментальные методы в экономике',
    specialization: 'Научная специальность',
    duration: '3–4 года',
    durationValue: 4,
    price: 150000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'Вступительные испытания по специальности',
    passingScore: 0,
    description: 'Подготовка исследователей в области экономических методов и моделирования.'
  },
  {
    id: '5.2.3',
    code: '5.2.3',
    level: EducationLevel.POSTGRADUATE,
    name: 'Региональная и отраслевая экономика',
    specialization: 'Научная специальность',
    duration: '3–4 года',
    durationValue: 4,
    price: 150000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'Вступительные испытания по специальности',
    passingScore: 0,
    description: 'Подготовка кандидатов наук в области региональной и отраслевой экономики.'
  },
  {
    id: '5.2.6',
    code: '5.2.6',
    level: EducationLevel.POSTGRADUATE,
    name: 'Менеджмент',
    specialization: 'Научная специальность',
    duration: '3–4 года',
    durationValue: 4,
    price: 150000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'Вступительные испытания по специальности',
    passingScore: 0,
    description: 'Подготовка исследователей в области теории и практики менеджмента.'
  },
  {
    id: '5.3.1',
    code: '5.3.1',
    level: EducationLevel.POSTGRADUATE,
    name: 'Общая психология, психология личности, история психологии',
    specialization: 'Научная специальность',
    duration: '3–4 года',
    durationValue: 4,
    price: 150000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'Вступительные испытания по специальности',
    passingScore: 0,
    description: 'Подготовка кандидатов наук в области психологии.'
  },
  {
    id: '5.10.1',
    code: '5.10.1',
    level: EducationLevel.POSTGRADUATE,
    name: 'Теория и история культуры, искусства',
    specialization: 'Научная специальность',
    duration: '3–4 года',
    durationValue: 4,
    price: 150000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: 'Вступительные испытания по специальности',
    passingScore: 0,
    description: 'Подготовка исследователей в области культуры и искусства.'
  },

  // ——— Среднее профессиональное образование – колледж ———
  {
    id: '07.02.01',
    code: '07.02.01',
    level: EducationLevel.SPO,
    name: 'Архитектура',
    specialization: 'Архитектура и дизайн',
    duration: '2 года 10 мес.',
    durationValue: 3,
    price: 90000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Конкурс аттестатов; Творческое испытание',
    passingScore: 4.2,
    description: 'Подготовка специалистов в области архитектуры на уровне СПО.'
  },
  {
    id: '08.02.15',
    code: '08.02.15',
    level: EducationLevel.SPO,
    name: 'Информационное моделирование в строительстве',
    specialization: 'BIM-технологии',
    duration: '2 года 10 мес.',
    durationValue: 3,
    price: 85000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Конкурс аттестатов',
    passingScore: 4.0,
    description: 'Работа с информационными моделями зданий и сооружений (BIM).'
  },
  {
    id: '54.02.01',
    code: '54.02.01',
    level: EducationLevel.SPO,
    name: 'Дизайн по отраслям',
    specialization: 'Графический дизайн, дизайн среды',
    duration: '2 года 10 мес.',
    durationValue: 3,
    price: 95000,
    format: [StudyFormat.FULL_TIME],
    exams: 'Конкурс аттестатов; Творческое испытание',
    passingScore: 4.2,
    description: 'Основы композиции и владение графическими пакетами по отраслям.'
  },

  // ——— Дополнительное профессиональное образование (по szu.ru/directions-of-training) ———
  {
    id: 'dpo-pk',
    code: 'ДПО',
    level: EducationLevel.DPO,
    name: 'Экспертиза и реставрация объектов культурного наследия',
    specialization: 'Программы повышения квалификации · 72 ак.ч',
    duration: '72 ак.ч',
    durationValue: 1,
    price: 15000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: '—',
    passingScore: 0,
    description: 'Курсы повышения квалификации: «Экспертиза и реставрация объектов культурного наследия» (15 000 ₽) и «Активные методы обучения в условиях реализации ФГОС нового поколения» для педагогов (800 ₽). Объём 72 ак.ч, форма очная и очно-заочная. По окончании — удостоверение установленного образца.'
  },
  {
    id: 'dpo-pp',
    code: 'ДПО',
    level: EducationLevel.DPO,
    name: 'Живопись',
    specialization: 'Программы профессиональной переподготовки · 72 ак.ч',
    duration: '72 ак.ч',
    durationValue: 1,
    price: 15000,
    format: [StudyFormat.FULL_TIME, StudyFormat.PART_TIME],
    exams: '—',
    passingScore: 0,
    description: 'Дополнительная образовательная программа предпрофессиональной подготовки «Живопись»: освоение жанров и технологий живописи, развитие творческих способностей. Объём 72 ак.ч, очная и очно-заочная форма. По окончании — сертификат ЧОУВО «Северо-Западный университет». Занятия ведёт член Союза художников России, лауреат всероссийских и международных выставок. К освоению допускаются все желающие. Начало занятий по мере комплектования групп.'
  },
  {
    id: 'dpo-podg-ris',
    code: 'ДПО',
    level: EducationLevel.DPO,
    name: 'Рисунок, живопись и композиция',
    specialization: 'Подготовка к творческим испытаниям',
    duration: '96 ак.ч',
    durationValue: 1,
    price: 25000,
    format: [StudyFormat.FULL_TIME],
    exams: '—',
    passingScore: 0,
    description: 'Подготовительные курсы для поступающих. Комплексная подготовка по изобразительному искусству.',
    tags: ['Подготовительные курсы']
  },
  {
    id: 'dpo-podg-rezh',
    code: 'ДПО',
    level: EducationLevel.DPO,
    name: 'Режиссура мультимедиа',
    specialization: 'Подготовка к поступлению на 55.05.01',
    duration: '72 ак.ч',
    durationValue: 1,
    price: 45000,
    format: [StudyFormat.FULL_TIME],
    exams: '—',
    passingScore: 0,
    description: 'Подготовительные курсы для поступающих на режиссуру кино и телевидения, профиль «Режиссёр мультимедиа».',
    tags: ['Подготовительные курсы']
  },
  {
    id: 'dpo-podg-diz',
    code: 'ДПО',
    level: EducationLevel.DPO,
    name: 'Дизайн',
    specialization: 'Подготовка к поступлению (54.02.01, 54.03.04)',
    duration: '72 ак.ч',
    durationValue: 1,
    price: 35000,
    format: [StudyFormat.FULL_TIME],
    exams: '—',
    passingScore: 0,
    description: 'Подготовительные курсы по графическому, коммуникационному и средовому дизайну.',
    tags: ['Подготовительные курсы']
  },
  {
    id: 'dpo-podg-arh',
    code: 'ДПО',
    level: EducationLevel.DPO,
    name: 'Архитектура',
    specialization: 'Подготовка к поступлению (07.02.01, 07.03.01, 07.03.02, 07.03.04)',
    duration: '72 ак.ч',
    durationValue: 1,
    price: 40000,
    format: [StudyFormat.FULL_TIME],
    exams: '—',
    passingScore: 0,
    description: 'Подготовительные курсы: композиция, рисунок. Подготовка к творческим испытаниям.',
    tags: ['Подготовительные курсы']
  }
];
